config/routes.rb
Rails.application.routes.draw do

  get 'user_pages/profile'
  get 'user_pages/region'
  get 'user_pages/tags'

  get 'welcome/index'

  resources :user
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :sources, shallow: true do
    resources :news_items do
    end
  end

  resources :regions, shallow: true do
    resources :news_items do
    end
  end

  resources :tags, shallow: true do
    resources :news_items
  end
  resources :news_items

  get 'welcome/index'

  root 'welcome#index'

end

app/views/layouts/_mainnavbar.html.haml
%nav#main-nav
  .navigation
    / search form visible on phone
    .search
      %form
        .search-wrapper
          %input.search-query.form-control{:autocomplete => "off", :name => "q", :placeholder => "Search...", :type => "text", :value => ""}/
          %button.btn.btn-link.icon-search{:name => "button"}
    / navigation items
    %ul.nav.nav-stacked
      / single navigation item
      %li.active
        = link_to sources_path do
          %i.icon-home 
          %span 
            Home
      %li
        = link_to sources_path do
          %i.icon-book
          %span
            Educación 
      %li
        = link_to sources_path do
          %i.icon-heart
          %span
            Salud
      %li
        = link_to sources_path do
          %i.icon-money
          %span
            Economía 
      %li
        = link_to sources_path do
          %i.icon-bullhorn
          %span
            Cultura

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  / application logo
  = link_to "TuConstituyes", sources_path, :class => "navbar-brand"
  / main nav toggler (show/hide)
  %a.toggle-nav.btn.pull-left{:href => "#"}
    %i.icon-reorder
  / dropdowns
  %ul.nav
    %li.dropdown.dark.user-menu
      -if @current_user
        = link_to @current_user.name, sources_path, :class => "dropdown-toggle"
      -else
        = link_to "Login", sources_path, :class => "dropdown-toggle"
  %form.navbar-form.navbar-right.hidden-xs
    %button.btn.btn-link.icon-search
    .form-group
      %input#q_header.form-control{:autocomplete => "off", :name => "q", :placeholder => "Search...", :type => "text", :value => ""}/

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TuConstituyes
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{:href => "https://fonts.googleapis.com/css?family=Oswald", :rel => "stylesheet", :type => "text/css"}/
  %body
    %wrapper
      %nav.navbar.navbar-default
        %container-fluid
          .navbar-header
            %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to 'TúConstituyes', root_path, class: 'navbar-brand'
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              = link_to root_path do
                Noticias
                %span.sr-only (current)
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Fuentes
                %span.caret
              %ul.dropdown-menu
                - @all_sources.each do |all_source|
                  %li
                    =link_to all_source.name, all_source
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Regiones
                %span.caret
              %ul.dropdown-menu
                - @all_regions.each do |all_region|
                  %li
                    =link_to all_region[:name], region_path(all_region[:id])
          = form_tag("/news_items", method: "get", class: 'navbar-form navbar-left') do
            .form-group
              = text_field_tag :query
              = submit_tag "Buscar", class: 'btn btn-default'
          %ul.nav.navbar-nav.navbar-right
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Mi cuenta
                %span.caret
              %ul.dropdown-menu
                %li
                  = link_to 'Mi perfil', user_pages_profile_path
                %li
                  = link_to 'Mi región', user_pages_region_path
                %li
                  = link_to 'Mis tags', user_pages_tags_path
            %li
              = link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete
      %container
        = yield